name: test-autograde
description: "Greeting!"
author : Aditya Eka
branding : 
  icon : 'check-circle'
  color : 'white'
inputs:
  kelas: # id input
    description: "kelas yang diberikan tugas"
    required: true
    default: ""
outputs:
  time: # id of output
    description: "Time greeting"
runs:
  using: "node12"
  main: "index.js"
