on: [push]

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    name: Job to greeting
    steps:
      - name: Hello action
        id: hello
        uses: masaditya/test-autograde@v3
        with:
          who-to-greet: "Ndasdos"
      - name: Get output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
